@MiniTicketSystem.Api_HostAddress = http://localhost:5019

GET {{MiniTicketSystem.Api_HostAddress}}/tickets
Accept: application/json

###

GET {{MiniTicketSystem.Api_HostAddress}}/tickets?status=Open&search=&page=1&pageSize=10
Accept: application/json

###

POST {{MiniTicketSystem.Api_HostAddress}}/tickets
Content-Type: application/json

{
  "title": "New ticket",
  "description": "Something broke"
}

###

PUT {{MiniTicketSystem.Api_HostAddress}}/tickets/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "id": "00000000-0000-0000-0000-000000000000",
  "title": "Updated ticket",
  "description": "Something broke, now fixed",
  "status": "Closed"
}

###

